name: Build and Test Dockerfile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build --cache-from=type=local,src=/tmp/.buildx-cache --target test -t cron:test .

    - name: Run Docker container
      run: docker run --name my-container -e CRON_WORKING='* * * * * echo working-great' -e CRON_NOTWORKING='* * * * echo nonworking' -d cron:test

    - name: Test Docker container
      run: docker exec my-container crontab -l | grep nonworking 

    - name: Check logging
      run: sleep 65; docker logs cron:test | grep working-great

    - name: Clean up
      run: docker rm -f my-container
